### ISSUE TITLE
Setup Inicial

### ISSUE THREAD

**Issue by Joabesv** [Joabesv/ufabc-next-ms-users#1]
- [x] Configurar Versão do Node no projeto -  #3 
- [x] Configurar versão do pnpm no projeto -  #3 
- [x] Configurar opções específicas para o vscode (Eslint, Prettier etc...) -  #3 
- [x] Configurar Renovate bot - #8 
- [x] Configurar pipeline - Partially made, see #12 
- [x] Configure Lint and format tools - #9 
- [x] #4
- [x] Configurar Typescript - #10 
- [x] #13
- [x] #11 - #18
- [x] Primeiro Hello World! #20

**Comment by Joabesv** [comment]
#3 PR para finalizar algumas tasks de setup!

**Comment by brMonteiro-G** [comment]
Finished 😁
